import './globals.css';
import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import { Montserrat } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const monserrat = Montserrat({
  subsets: ['latin'],
  // weight: ['200', '400', '600', '700', '800', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background antialiased',
          monserrat.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
